
<div class="row">

    <div class="col-md-4">
    <?php echo $this->render('doscg/index/finding_x_y_z');?>
    </div>
    <div class="col-md-4">
    <?php echo $this->render('doscg/index/calculate');?>
    </div>
    <div class="col-md-4">
    <?php echo $this->render('doscg/index/chat');?>
    </div>
    <div class="col-md-12" style=" padding-top: 25px;">
    <?php echo $this->render('doscg/index/map');?>
    </div>
    
    </div>
    




